version: '3'

services:  
  mongodb:
    image: 'mongo:latest'
    # ports:
    #   - "27017:27017"
    volumes:
      - ./data/db:/data/db
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./app:/code
    links:
      - mongodb
    # command: ["python", "app.py"]
